
GET /users HTTP/1.1
Host: localhost:8081

###
POST /users HTTP/1.1
Host: localhost:8081
Content-Type: application/x-www-form-urlencoded

name=fiki3&id=3


###
DELETE /users/1 HTTP/1.1
Host: localhost:8081


###
PATCH /users/2 HTTP/1.1
Host: localhost:8081
Content-Type: application/x-www-form-urlencoded

name=fiki122&id=2


----------

###
POST /auth/register HTTP/1.1
Host: localhost:8081
Content-Type: application/x-www-form-urlencoded

email=fikki@gmail.com&id=1&password=1234567890

###
GET /auth/register HTTP/1.1
Host: localhost:8081


###
POST /auth/login HTTP/1.1
Host: localhost:8081
Content-Type: application/x-www-form-urlencoded

email=fikki@gmail.com&password=1234567890


### // register

POST /auth/register HTTP/1.1
Host: localhost:8081
Content-Type: application/x-www-form-urlencoded

id=1&email=fikki@gmail.com&password=1234567890

### // list semua user
GET http://localhost:8081/auth/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZXhwIjoxNzYyNTA4NzU5LCJpYXQiOjE3NjI0MjIzNTl9.TIymty-ZFcULf4Z1O5WhqFwCbd4x10KLSA4phkik0SE



### //login
POST http://localhost:8081/auth/login
Content-Type: application/x-www-form-urlencoded

id=1&email=fikki@gmail.com&password=1234567890

### // upload file
PATCH http://localhost:8081/auth/users/1/profile-picture
Content-Type: multipart/form-data; boundary=MyBoundary
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZXhwIjoxNzYyNTA4NzU5LCJpYXQiOjE3NjI0MjIzNTl9.TIymty-ZFcULf4Z1O5WhqFwCbd4x10KLSA4phkik0SE

--MyBoundary
Content-Disposition: form-data; name="picture"; filename="tes.jpeg"
Content-Type: image/jpeg

< /home/fiki/Downloads/tes.jpeg
--MyBoundary--
